version: '2'

services:

  db:
    image: postgres
    env_file: secrets.env
    volumes:
      - ./dbdata:/var/lib/postgresql/data

  web:
    # Docker hack to wait until Postgres is up, then run stuff.
    command: bash -c "while ! nc -w 1 -z db 5432; do sleep 0.1; done; ./manage.py migrate; sh -c 'npm run hot-reload & ./manage.py runserver 0.0.0.0:8000'"
    image: django
    container_name: hallway_web
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/code
    depends_on:
      - db
    environment:
      IN_DOCKER: 1
    env_file: secrets.env

  webserver:
    image: jumanjiman/caddy
    depends_on:
      - web
    volumes:
      - .:/code
    ports:
      - "80:8000"
      - "3000:3000" # expose 3000 since this is node's (proxied) hot reload port
    command: -conf /code/CaddyFile.dev