# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0003_remove_message_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
