# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 21:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0005_conversation_discussion_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='discussion_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.DiscussionGroup'),
        ),
    ]
