# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 17:46
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_auto_20161012_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscussionGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator])),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('hash_key', models.CharField(max_length=32)),
                ('associated_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invites', to=settings.AUTH_USER_MODEL)),
                ('discussion_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_groups', to='accounts.DiscussionGroup')),
            ],
        ),
    ]
